name: mth5-docs
channels:
  # Don't change to pkgs/main, as it causes random timeouts in readthedocs
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - h5py>=2.10.0
  - ipykernel
  - ipython
  - jupyter_client
  - nbsphinx
  - obspy
  - setuptools
  - sphinx>=2.3
  - sphinx_rtd_theme>=0.4
  - sphinx-autoapi
  - xarray
  - PyYAML
  - pandas
  - pip:
    - loguru
    - mt-metadata
